name: todo-app
services:
  nginx:
    image: nginx:1.17
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8000:80
    depends_on:
      frontend:
        condition: service_started  # Attendre que le service soit démarré
      backend:
        condition: service_started
    networks:
      - app-network
    restart: on-failure

  frontend:
    image: "node:16-alpine"  # Utiliser une image Alpine plus légère
    working_dir: /app
    environment:
      - NODE_ENV=development
      - WDS_SOCKET_PORT=0
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm start"  # Utiliser sh au lieu de bash avec Alpine
    networks:
      - app-network

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/usr/src/app
    ports:
      - "8001:3001"
    command: "python src/server.py"
    environment:
      - DEBUG=true
      - MONGODB_URI=mongodb+srv://gaouditz:Fast-api@cluster0.mxzeyxz.mongodb.net/todo-app?retryWrites=true&w=majority&appName=Cluster0
    networks:
      - app-network

networks:
  app-network:
    driver: bridge